update documentation
terraform-google-modules/terraform-example-foundation pull request #301
Opened 2020-12-08 19:54 UTC by gaspar-chilingarov

- Rename G Suite -> Google Workspace
- Add use case for deployment under specific folder

2020-12-09 01:17 UTC, bharathkkb requested changes
Thanks for the PR @gaspar-chilingarov 
Looks like this was based off of the main branch, could you base off of `develop` branch?

2020-12-09 22:10 UTC, rjerrems approved these changes
LGTM

2020-12-10 02:36 UTC, bharathkkb approved these changes
LGTM, minor suggestion

2020-12-10 02:36 UTC, bharathkkb commented on 0-bootstrap/README.md
> +1. Cloud Identity / Google Workspace groups for organization and billing admins
We are working with a tech editor who suggested this in the docs
```suggestion
1. Cloud Identity / Google Workspace  (formerly G Suite) groups for organization and billing admins
```

2020-12-14 13:56 UTC, gaspar-chilingarov commented
more changes to update the documentation

2020-12-14 16:10 UTC, bharathkkb approved these changes

2020-12-14 16:11 UTC, merged