fix: Pin network-peering for terraform 0.12
terraform-google-modules/terraform-example-foundation pull request #333
Opened 2021-02-09 12:57 UTC by deas

The release of `network-peering` 3 which rolled to `terraform` 0.13 broke current master:

```
Step #1 - "tf plan validate all": Warning: Provider source not supported in Terraform v0.12
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":   on .terraform/modules/peering/modules/network-peering/versions.tf line 20, in terraform:
Step #1 - "tf plan validate all":   20:     google = {
Step #1 - "tf plan validate all":   21:       source  = "hashicorp/google"
Step #1 - "tf plan validate all":   22:       version = "<4.0,>= 2.12"
Step #1 - "tf plan validate all":   23:     }
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": A source was declared for provider google. Terraform v0.12 does not support
Step #1 - "tf plan validate all": the provider source attribute. It will be ignored.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported block type
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":   on .terraform/modules/peering/modules/network-peering/versions.tf line 26, in terraform:
Step #1 - "tf plan validate all":   26:   provider_meta "google" {
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Blocks of type "provider_meta" are not expected here.
```

This PR fixed it for me.

2021-02-12 16:04 UTC, bharathkkb requested changes
Thanks for the PR @deas 
Could you target the develop branch which supports 0.13 instead and pin to `3.0`

2021-02-12 16:10 UTC, deas commented
@bharathkkb Sure, but what about people naive like me trying out master? Any rough guess when `develop` will be ready to go into `master`?

2021-02-22 03:01 UTC, rjerrems commented
It may be worthwhile considering a patch to master @bharathkkb if this is breaking people on version 0.12.x, given that is the supported version of terraform on master and what many people will be working with if they clone the repo rather than specifically targeting a release?

We can then update to version 3.0 with the next release along with support for 0.13, when that eventually happens.

2021-02-22 04:16 UTC, bharathkkb commented
@rjerrems sg, my only concern was that testing was broken on main due to our changes to tests in develop. This is a small change so should not be an issue.

2021-02-22 04:16 UTC, bharathkkb approved these changes

2021-02-23 09:27 UTC, deas commented
A bit OT, but what's actually holding `develop` back from being merged into `master`?

Are there (many?) known direct or indirect (modules?) issues with example-foundation and terraform >= 0.13?

2021-02-24 00:44 UTC, bharathkkb commented
Hi @deas 
The initial decision for having a develop branch was to 
- prevent breakage while we were transitioning upstream modules to use 0.13
- update tests to accommodate new patterns

Both of these are now complete however we still need to manually validate some of the steps to ensure that our README instructions are up to date.

2021-03-10 04:57 UTC, rjerrems commented
hi @deas - can you do a `terraform fmt` on this? It looks like the linting tests are failing because of that

2021-03-10 23:15 UTC, rjerrems approved these changes
LGTM

cc: @bharathkkb

2021-03-10 23:17 UTC, merged

2021-03-10 23:17 UTC, rjerrems commented
Thanks @deas !