upgrade version for dependant CFT modules
terraform-google-modules/terraform-example-foundation pull request #339
Opened 2021-02-18 06:44 UTC by ericyz

2021-02-18 16:58 UTC, morgante approved these changes

2021-02-18 18:01 UTC, bharathkkb requested changes
Thanks for the PR @ericyz

2021-02-18 18:01 UTC, bharathkkb commented on 1-org/envs/shared/versions.tf
> +  required_version = ">=0.13, <0.14"
there seems to be conflicting `terraform` blocks with required_version. We should keep these to `required_version >= 0.13` to allow users flexibility

2021-02-18 18:02 UTC, bharathkkb commented on 1-org/envs/shared/versions.tf
> +  required_version = ">=0.13, <0.14"
this seems to be in other updated versions files as well

2021-02-25 16:43 UTC, bharathkkb commented on 1-org/envs/shared/versions.tf
>  terraform {
@ericyz we should remove this extraneous `terraform` block here and throughout

2021-03-02 03:34 UTC, bharathkkb commented
/gcbrun

2021-03-02 07:25 UTC, bharathkkb approved these changes

2021-03-02 16:16 UTC, merged