chore: fixes for issue 489
terraform-google-modules/terraform-example-foundation pull request #509
Opened 2021-07-23 00:08 UTC by mark1000

2021-07-23 16:49 UTC, bharathkkb requested changes
Thanks @mark1000 
Can we also update the other [stages](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/3-networks#deploying-with-cloud-build)

2021-07-23 21:06 UTC, mark1000 commented
I think I caught all the files?

2021-07-27 23:46 UTC, bharathkkb approved these changes

2021-07-27 23:47 UTC, bharathkkb commented on 1-org/README.md
> +   from the gcp-environments directory. If you run them from another directory,
```suggestion
   from the gcp-policies directory. If you run them from another directory,
```

2021-07-27 23:49 UTC, merged