fix: Issue #628 Failed Cloud Build plan in 1-org using cloud build SA from TFV
terraform-google-modules/terraform-example-foundation pull request #629
Opened 2022-02-05 09:21 UTC by ipv1337

This fixed my issue #628.

2022-02-09 07:13 UTC, bharathkkb requested changes
Thanks for the PR, could you also add a google_folder_iam_member binding if `var.parent_folder != ""`?

2022-02-11 19:05 UTC, ipv1337 commented
> Thanks for the PR, could you also add a google_folder_iam_member binding if `var.parent_folder != ""`?

Let me know if the recent commit is what you are looking for @bharathkkb.

2022-02-17 01:59 UTC, bharathkkb reviewed
It looks like we will actually need `roles/iam.securityReviewer` as [TFV will need to get IAM policy associated with any resource](https://github.com/GoogleCloudPlatform/terraform-validator/blob/8f1cc1a0d8d7feba66d8eb67f16467a3d930ab82/docs/user_guide.md#required-permissions) x-ref: https://github.com/terraform-google-modules/terraform-example-foundation/issues/546. It also looks like `organizationRoleViewer` can only be granted at the org level

2022-02-17 01:59 UTC, bharathkkb commented on 0-bootstrap/main.tf
> +  role   = "roles/iam.organizationRoleViewer"
```suggestion
  role   = "roles/iam.securityReviewer"
```

2022-02-17 01:59 UTC, bharathkkb commented on 0-bootstrap/main.tf
> +  role   = "roles/iam.organizationRoleViewer"
```suggestion
  role   = "roles/iam.securityReviewer"
```

2022-02-22 05:11 UTC, bharathkkb approved these changes

2022-02-22 05:11 UTC, merged