Feature/split network step
terraform-google-modules/terraform-example-foundation pull request #735
Opened 2022-06-07 17:34 UTC by mauro-cit

Fixes #672 
Fixes #671 

Some notes about the changes done by this PR:
- As we have separated the step 3-networks, the guide for doing that was through the **enable_hub_and_spoke** variable.
- Basically the resources that required the variable enable_hub_and_spoke as true we put on **3-networks-hub-and-spoke**, the resources that doesn't we put on **3-networks-dual-svpc**. We also moved the resources that were depending on these ones.
- We also removed the variable **enable_hub_and_spoke_transitivity** from the Dual Shared VPC mode since it was only used when the **enable_hub_and_spoke** variable was true
- A script called **restore_tf_files.sh** was also created to undo the actions that the "disable_tf_files.sh" was doing to the *.tfvars and backend files

2022-06-18 01:21 UTC, daniel-cit requested changes
The Hub & Spoke Transitivity module

https://github.com/mauro-cit/terraform-example-foundation/tree/feature/split-network-step/3-networks-dual-svpc/modules/transitivity

should be removed from the dual svpc version

there are also some fixes on the readme and `shared.auto.example.tfvars` files in the Hub and Spoke version

2022-06-18 01:21 UTC, daniel-cit commented on 3-networks-hub-and-spoke/shared.auto.example.tfvars
> +target_name_server_addresses = ["192.168.0.1", "192.168.0.2"]
```suggestion
target_name_server_addresses = ["192.168.0.1", "192.168.0.2"]

//enable_hub_and_spoke_transitivity = true
```

missing the enable_hub_and_spoke_transitivity  variable in the right file example file

2022-06-18 01:21 UTC, daniel-cit commented on 3-networks-hub-and-spoke/README.md
> +This step makes use of the **Dual Shared VPC** architecture mode, and more details can be found described at the **Networking** section of the [Google cloud security foundations guide](https://cloud.
```suggestion
This step uses the **Hub and Spoke** architecture  mode.
More details can be found at the **Networking** section of the [Google cloud security foundations guide](https://cloud.google.com/architecture/security-foundations/networking#hub-and-spoke).
To enabled **Hub and Spoke** [transitivity](https://cloud.google.com/architecture/security-foundations/networking#hub-and-spoke_transitivity) set the variable `enable_hub_and_spoke_transitivity ` to `true`.
To see the version that makes use of the **Dual Shared VPC** architecture mode check the step [3-networks-dual-svpc](../3-networks-dual-svpc).
```

2022-06-22 22:06 UTC, bharathkkb reviewed
Thanks for the PR @mauro-cit 
We can also remove some of the conditional logic we no longer need like in https://github.com/terraform-google-modules/terraform-example-foundation/blob/997d699b8b35f7539ac632230ef86033d630952a/3-networks-dual-svpc/modules/base_shared_vpc/variables.tf#L27

2022-06-22 22:06 UTC, bharathkkb commented on 3-networks-hub-and-spoke/README.md
> +- Set up base and restricted shared VPCs with default DNS, NAT (optional), Private Service networking, VPC service controls, on-premises Dedicated or Partner Interconnect, and baseline firewall rules
Lets update this to reflect hub and spoke model i.e base and restricted hubs and corresponding spokes.

2022-06-22 22:06 UTC, bharathkkb commented on 3-networks-hub-and-spoke/envs/shared/README.md
> +# 3-networks-hub-and-spoke/shared
Let's also call out below that hubs are setup here.

2022-06-30 12:46 UTC, mauro-cit commented on 3-networks-hub-and-spoke/modules/hierarchical_firewall_policy/main.tf
> +resource "google_compute_organization_security_policy_rule" "rule" {
Issue created: https://github.com/terraform-google-modules/terraform-example-foundation/issues/746

2022-06-30 12:47 UTC, mauro-cit commented on 3-networks-hub-and-spoke/modules/hierarchical_firewall_policy/main.tf
> +resource "google_compute_organization_security_policy_rule" "rule" {
@bharathkkb is there any other module you want it to be upstreamed as well?

2022-07-01 05:38 UTC, bharathkkb approved these changes
LGTM with a suggestion

2022-07-01 05:38 UTC, bharathkkb commented on 3-networks-hub-and-spoke/modules/base_env/main.tf
> +  enable_transitivity       = true
We should still have enable_hub_and_spoke_transitivity with default false.

2022-07-01 05:38 UTC, bharathkkb commented on 3-networks-hub-and-spoke/envs/shared/net-hubs.tf
> +  restricted_net_hub_project_number = try(data.google_projects.restricted_net_hub.projects[0].number, null)
@mauro-cit does this need a try? If so a comment will be useful for understanding usecase.

2022-07-06 15:11 UTC, merged